# Generated by Django 3.2.3 on 2021-05-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('Nombre', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name=' Ingrese Nombre:')),
                ('Apellido', models.CharField(max_length=20, verbose_name='Ingrese Apellido: ')),
                ('Correo', models.CharField(max_length=45, verbose_name='Ingrese Correo: ')),
                ('Telefono', models.IntegerField(verbose_name='Ingrese Telefono: ')),
                ('Direccion', models.CharField(max_length=40, verbose_name='Ingrese Direccción: ')),
                ('Rut', models.CharField(max_length=12, verbose_name='Ingrese Rut: ')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ID_cliente', models.IntegerField()),
                ('Nombre_cliente', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name=' Ingrese Nombre:')),
                ('Apellido_cliente', models.CharField(max_length=20, verbose_name='Ingrese Apellido: ')),
                ('Correo_cliente', models.CharField(max_length=45, verbose_name='Ingrese Correo: ')),
                ('Telefono_cliente', models.IntegerField()),
                ('Direccion_cliente', models.CharField(max_length=40, verbose_name='Ingrese Direccción: ')),
            ],
        ),
        migrations.CreateModel(
            name='Comprobante_ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Detalle_venta', models.CharField(max_length=20, verbose_name=' Ingrese Nombre:')),
                ('Precio_adquisicion', models.CharField(max_length=20, verbose_name='Ingrese Apellido: ')),
                ('Precio_Venta', models.CharField(max_length=20, verbose_name='Ingrese Apellido: ')),
                ('Total_pedido', models.IntegerField(verbose_name='Ingrese Correo: ')),
                ('Fecha_venta', models.IntegerField(verbose_name='Ingrese Apellido: ')),
            ],
        ),
        migrations.CreateModel(
            name='Estado_de_Resultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ingreso_Total', models.IntegerField()),
                ('Costo_Total', models.IntegerField()),
                ('Resultado_total', models.IntegerField()),
                ('Existencias_eerr', models.IntegerField()),
                ('Margen_perdida', models.IntegerField()),
                ('Resultado_final', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo_Gasto', models.CharField(max_length=25, verbose_name='Ingrese Correo: ')),
                ('Fecha_Gasto', models.IntegerField(verbose_name='Ingrese Apellido: ')),
                ('Descripcion_Gasto', models.IntegerField(verbose_name='Ingrese Correo: ')),
                ('monto_Gasto', models.IntegerField(verbose_name='Ingrese Correo: ')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('Codigo_Inventario', models.IntegerField(verbose_name=' Ingrese Codigo:')),
                ('Nombre', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name=' Ingrese Nombre:')),
                ('Unidades', models.IntegerField(verbose_name='Ingrese Unidades: ')),
                ('Precio', models.IntegerField(verbose_name='Ingrese Precio: ')),
                ('Proyeccion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo_Pedido', models.IntegerField(verbose_name=' Ingrese Nombre:')),
                ('ID_cliente', models.IntegerField(verbose_name='Ingrese Correo: ')),
                ('Descripcion_pedido', models.IntegerField(verbose_name='Ingrese Correo: ')),
                ('Cantidad_pedido', models.IntegerField(verbose_name='Ingrese Correo: ')),
                ('Valor_pedido', models.IntegerField(verbose_name='Ingrese Telefono: ')),
                ('Fecha_pedido', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('Codigo_Producto', models.IntegerField(verbose_name=' Ingrese codigo:')),
                ('Nombre', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name=' Ingrese Nombre:')),
                ('Fecha', models.IntegerField(verbose_name='Ingrese Apellido: ')),
                ('Cantidad_minima', models.IntegerField()),
                ('Cantidad_maxima', models.IntegerField()),
                ('Costo_total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Detalle_venta', models.CharField(max_length=20, verbose_name=' Ingrese Nombre:')),
                ('tipo_vnt', models.CharField(max_length=20, verbose_name=' Ingrese Nombre:')),
                ('Precio_adquisicion', models.CharField(max_length=20, verbose_name='Ingrese Apellido: ')),
                ('Precio_Venta', models.CharField(max_length=20, verbose_name='Ingrese Apellido: ')),
                ('Codigo_Pedido', models.CharField(max_length=25, verbose_name='Ingrese Correo: ')),
                ('Cantidad_pedido', models.IntegerField(verbose_name='Ingrese Correo: ')),
                ('Inventario_fisico', models.IntegerField(verbose_name='Ingrese Correo: ')),
                ('Fecha_venta', models.IntegerField(verbose_name='Ingrese Apellido: ')),
            ],
        ),
    ]
